GET http://localhost:3001
Authorization: Bearer eyJhbGcsiOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJJZCI6NSwidXNlckVtYWlsIjoia2FjcGVyQGdtYWlsLmNvbSJ9LCJpYXQiOjE2MTE3ODI4NjksImV4cCI6MTYxMTc4MzE2OSwiYXVkIjoiNSJ9.jwql5kIr3xpyrw_QBncPffDEyyivAlD9_YenX-ca2c4

###Login Route
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "kacper@gmail.com",
  "password": "Haslo123"
}


###Register Route
POST http://localhost:3001/auth/register
Content-Type: application/json

{
  "email": "kacper@gmail.com",
  "password": "Haslo123",
  "name": "Kacper Kedzierski"
}

###Refresh token Route
POST http://localhost:3001/auth/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJJZCI6NSwidXNlckVtYWlsIjoia2FjcGVyQGdtYWlsLmNvbSJ9LCJpYXQiOjE2MTE3ODI4NjksImV4cCI6MTY0MzM0MDQ2OSwiYXVkIjoiNSJ9.elD1W5OfgAOOcELcY2f-aveZM6q2TegAnelpm6U-uQc"
}

###Logout Route
DELETE http://localhost:3001/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTI1ODcyOTIsImV4cCI6MTYyNDE0NDg5MiwiYXVkIjoiNWVlYTBlOTlkMTU3ZjYzZjNlMzYxYjQxIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.OGfV-n2fsuV2D5nvUGEzU7KLtkbIy1Pmm4DwxB75MKU"
}